services:
  YTdownloader:
    build:
      context: https://github.com/procrastinando/Selfhosted-Youtube-Downloader.git#main
    image: procrastinando/Selfhosted-Youtube-Downloader:latest
    container_name: YTdownloader
    ports:
      - 7860:7860
    environment:
      GROQ_API_KEYS: gsk-aaaaaaaaa,gsk-bbbbbbbbb,gsk-ccccccccc
      WHISPER_MODEL_ID: whisper-large-v3
      USER_ID: admin
      USER_PASSWORD: password
    volumes:
      - downloader:/downloader
    restart: unless-stopped

volumes:
  downloader: