services:
  YTdownloader:
    build:
      context: https://github.com/procrastinando/Selfhosted-Youtube-Downloader.git#main
    image: procrastinando/Selfhosted-Youtube-Downloader:latest
    container_name: YTdownloader
    ports:
      - 7860:7860
    environment:
      GROQ_API_KEYS: ["gsk_aaaaaaa", "gsk_bbbbbbb", "gsk_ccccccc"]
      WHISPER_MODEL_ID: "whisper-large-v3"
    volumes:
      - downloader:/downloader
    restart: unless-stopped

volumes:
  downloader: